version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: open-webui-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app/backend
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: open-webui-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    environment:
      - VITE_BACKEND_URL=http://backend:8080
    restart: unless-stopped
